### ISSUE TITLE
Address NAT traversal

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#321]
- [x] determine we can use libp2p's solution

**Comment by lucksus** [comment]
Ok, so I've tried https://github.com/libp2p/go-libp2p-nat from within node.go. What I understand it can do is to create port mappings via UPnP, if the gateway supports that. 

But seems that here on the holodeck that is not the case. libp2p-nat finds a NAT device and tries to create mappings but does not succeed. I've tried https://github.com/ccding/go-stun/ to find out more about our NAT and got these outputs:

For 4229
```
$ go-stun
NAT Type: Port restricted NAT
External IP Family: 1
External IP: 45.28.137.157
External Port: 56639
```

For OfficeBridge
```
$ go-stun
NAT Type: Port restricted NAT
External IP Family: 1
External IP: 198.27.210.82
External Port: 49822
```

**Comment by lucksus** [comment]
I think we need different strategies here:

1. Trying to create a mapping (using  https://github.com/libp2p/go-libp2p-nat). If the local NAT supports that, that would be the best case since only then it is guaranteed that our node is reachable from the outside without us initiating a connection first.
2. Falling back to calling a STUN server  (using https://github.com/ccding/go-stun/). Q: do we just one of these public STUN servers: https://gist.github.com/zziuni/3741933 ? Or do we run our one / or even STUN logic to bs?
3. Put out a warning and request to the user to set-up their firewall to forward a port.

**Comment by zippy** [comment]
That sounds good. For my part here's the output if that's helpful:

```
NAT Type: Port restricted NAT
External IP Family: 1
External IP: 216.227.83.230
External Port: 39210
```
Can you push a branch I and I could try the libp2p-nat from here?

**Comment by lucksus** [comment]
pushed branch.
I think I have to revise my position on STUN - I don't think it can help us since we need other machines than the STUN server to initiate connections to the local node. (https://stackoverflow.com/questions/44879935/how-to-make-use-of-stun-in-p2p). So we need the UPnP working. I have checked our router here and it does support UPnP and it is activated but it didn't see go-libp2p-nat's request. I'm trying other libraries of which there are many..

**Comment by lucksus** [comment]
Ok, i've tried several other NAT UPnP libs and they all didn't work. Found out it's the local setup with two routers and a NAT behind a NAT.. The main router here on the Holodeck does not support UPnP, so I can't really test this here. I will think about what we would want/need to add to the bootstrap server but will take another ticket then and work on this again when I'm back in Dortmund with a better network setup to test on.

**Comment by lucksus** [comment]
Check libp2p's new NAT stuff in [BasicHost](https://github.com/libp2p/go-libp2p/blob/master/p2p/host/basic/basic_host.go)
