### ISSUE TITLE
Zygo Initial Code

### ISSUE THREAD

**Issue by GerryG** [metacurrency/holochain#33]
In the zygo code that is stored when you create a holochain,
what does "(mod entry 2)" do? What is 'mod' here?

**Comment by zippy** [comment]
This is my initial trivial validation of a trivial entry type.  The entry type is just a single number, and the validation rule is that it is odd!  This code is changing soon, because the templates created by GenDev will be of an actually useful holochain app, probably a simple distributed chat app.
