### ISSUE TITLE
As an app dev, I want the ability to retrieve all links on an entry, regardless of tag. Therefore, I can leave tag null on a call to the getLink function.

### ISSUE THREAD

**Issue by rayzer42** [metacurrency/holochain#419]
This way, I can use links as an array or associative array.

**Comment by artbrock** [comment]
I don't think this should happen by failing to provide the semantic tag though. This should probably be from passing a control parameter for ALL.

I say this because it seems easy for a developer to forget to specify the tag and then the end user gets very erratic behavior of unexpected things retrieved. Forgetting a parameter shouldn't make the function appear to be working as expected with the parameter.

**Comment by rayzer42** [comment]
Agreed!

**Comment by zippy** [comment]
Hmm this isn't so clear.  The current call is: `getLink(base,tag,[options])`  If you don't want this to work by passing in an empty string to the tag, then it seems that the tag itself should be moved into the options. 

 But I don't like that because then it means that for most calls you'ld be doing something like `getLInk(base,{Tag:"sometag"})`  and then when you want them all you would do something like `getlinks(base,{AllTags:true})`  

The above doesn't seem that elegant to me.   It seems so much easier to understand that the empty tag (i.e. `getlink(base,"")) means get all tags.  

The other option would be to have a whole separate function   `getAllLinks(base,[options])`  But I hate adding in too many functions.

BTW this function should be renamed to getLinks  (plural).

**Comment by artbrock** [comment]
Yes to plural.

And I get passing null string as an argument makes things easier. I'm good with it as long as you have to specify a null string, not just leave it out.  I think it will probably lead to some sloppy programming where people do it thinking: "I only ever put one kind of tag on here."  But whatever, we can't protect too much against people doing dumb stuff.

Yes... `getLinks(base,"",[options])`

**Comment by rayzer42** [comment]
I think the `getAllLinks(base, [option])` is the most elegant, but understand the added overhead of new core functions. Happy it's working as `getLinks(base,"",[options])`!
