### ISSUE TITLE
Makefile bug on windows

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#512]
for some reason the line:

`REPO = $(CURDIR:$(GOPATH)/src/%=%)` 

doesn't work on windows machines.  To get make working we had to hard code that line to the actual repo path.

**Comment by zippy** [comment]
Hey @timotree3, wanna work on this one?

**Comment by timotree3** [comment]
Yes. In order for me to understand the problem please provide the following information if possible:

- The version of make installed
- The inputs you gave (command ran, environment variable changed, etc.)
- Any changes that happened in your folder after running the command
- What output the command gave on the command prompt

**Comment by rayzer42** [comment]
@timotree3, maybe I can save some time here. Your pops and I actually did determine what is going wrong, we just didn't know how to fix it, and hardcoded the path so we move forward. The problem is that in windows the directory separators are backslashes, so the front slashes you have embedded in the match string do not actually match. If you still need me to provide the information you asked for, I will. Just let me know. Thanks, Timo!
