### ISSUE TITLE
error not thrown on commit when link fails validation

### ISSUE THREAD

**Issue by rayzer42** [metacurrency/holochain#556]

**Comment by zippy** [comment]
I have now run some tests on this, and I can't reproduce the problem.  It seems like if you don't validate the links entry type on commit you get the exact same error handling as you do when a regular entry fails its validation.  

If you are talking about failing validateLink function, this can't actually throw an error, because that happens at dht put time of the link, not at commit time.

**Comment by rayzer42** [comment]
Yes @zippy, this should have said validateLink. Sorry for the confusion, and thanks for letting me know that the callback does not happen at commit time.
