### ISSUE TITLE
Dump DHT as JSON

### ISSUE THREAD

**Issue by philipbeadle** [metacurrency/holochain#565]
Same as for 561 Dump Chain as JSON.

**Comment by clarenceb** [comment]
As discussed, the existing DHT dump to string contains binary encoded values so the output looks weird.

The proposed JSON output will look something like in this gist: https://gist.github.com/clarenceb/1b301fd802d4a5a33b3cac706153cf1b

Please provide feedback on whether this is ok.

If we can decode the binary values or store them in a more human-readable manner then it would make the DHT JSON dump more useful.

**Comment by clarenceb** [comment]
I have a working implementation here: https://github.com/clarenceb/holochain/commit/8b16cbaed8684e597819ca8ba3d2e9ae8bb9ceee

But I want to add more test cases and also refactor code to remove duplication in functions `dht.String()` and `dht.JSON()` and also `dht.DumpIdx()` and `dht.DumpIdxJSON()`.

Also, because of weird characters in the "value" encoding, I had to create a function to strip out some non-printable chars (see `utils.EscapeJSONValue`).  There might be a nicer way to do this or it might not be necessary when if the encoding of this field is changed.

A real DHT dump can be seen in this gist: https://gist.github.com/clarenceb/389e186995b11e29a2206aa67df4458e

**Comment by clarenceb** [comment]
PR submitted and build passing: https://github.com/metacurrency/holochain/pull/569
