### ISSUE TITLE
Create a :develop and :master docker image depending on branch

### ISSUE THREAD

**Issue by philipbeadle** [metacurrency/holochain#571]
The develop branch is going to be used for most of the new app development ie HoloChat and Clutter etc so we need to be able to test against the develop branch in CI.

**Comment by philipbeadle** [comment]
Merged

**Comment by clarenceb** [comment]
I believe that this is not implemented correctly since the Dockerfile uses `RUN go get -d -v github.com/Holochain/holochain-proto` to fetch the source code.  `go get` fetches code from the `master` branch.  This means the Docker image tagged `metacurrency/holochain:develop` actually uses code from the wrong branch.
